### ISSUE TITLE
Where are the releases?

### ISSUE THREAD

**Issue by ehsmaes** [disneystreaming/ssm-helpers#20]
I'm on a Mac and I found your tool to be very useful. However, I decided to try it on a pc and went looking for a download link. It turns out that the "Releases" link in the readme just links back to the same page. Where are the releases for other operating systems?

**Comment by rothgar** [comment]
You can find the Windows release in a zip file on the releases page of the repo. Windows should also be able to use the docker command in the README or the deb installation if you're using wsl2

https://github.com/disneystreaming/ssm-helpers/releases
