### ISSUE TITLE
Upgrade sdk-go to 1.37+ for SSO support

### ISSUE THREAD

**Issue by jfunnell** [disneystreaming/ssm-helpers#64]
Hi, this tool is pretty nice but I haven't been able to use it much because it doesn't work for AWS SSO profiles.
I figure maybe instead of politely waiting, it would be better to just ask if you guys are able to bump the aws-sdk dependency version to a later one that supports SSO profiles. According to google, that's version 1.37 and up.

If this is possible, I could recommend this to my team instead of maintaining my homegrown script.

**Comment by raserma** [comment]
This would be of great interest for my team as well as we are fully working with AWS SSO nowadays 🙏

**Comment by ncatelli** [comment]
Hello, I just wanted to follow up on this issue to let you know that the aws-go-sdk was update in #65 and should now be above v1.37.
